import { product } from '../model/product';

export const MOCKDATA : product[] = [{
    description:'description1',
    maximumQuantity:'maximumQuantity1',
    name:'name',
    productId:'productId',
    unitPrice:'110'
},
{
    description:'description1',
    maximumQuantity:'maximumQuantity1',
    name:'name',
    productId:'productId',
    unitPrice:'230'
},
{
    description:'description1',
    maximumQuantity:'maximumQuantity1',
    name:'name',
    productId:'productId',
    unitPrice:'450'
},
{
    description:'description1',
    maximumQuantity:'maximumQuantity1',
    name:'name',
    productId:'productId',
    unitPrice:'560'
},
{
    description:'description1',
    maximumQuantity:'maximumQuantity1',
    name:'name',
    productId:'productId',
    unitPrice:'330'
},
{
    description:'description1',
    maximumQuantity:'maximumQuantity1',
    name:'name',
    productId:'productId',
    unitPrice:'111'
},
{
    description:'description1',
    maximumQuantity:'maximumQuantity1',
    name:'name',
    productId:'productId',
    unitPrice:'222'
},]